Improve gostudy.py
fyre-0/r-IGCSEBot pull request #66
Opened 2024-01-02 06:10 UTC by emergenitro

Hi, 

Changed gostudy.py slightly due to redundancy in the code and large use of if/else statements. This should make it slightly more efficient. Additionally, I apologise for the edits on app.py, I had the Black formatter on and it auto-formatted, and I noticed it just when I made this PR so just ignore app.py (it should be formatted better now though). Just double check gostudy.py

2024-01-03 04:03 UTC, Sachin-dot-py requested changes
This pull request can be merged once the permissions issue in the `/gostudy` command is resolved.

2024-01-03 04:03 UTC, Sachin-dot-py commented on src/gostudy.py
> +    user_id = interaction.user.id if user is None else user.id
In this updated `/gostudy` command code there's no isModerator check when choosing a particular user so anyone would be able to Study Mute another member.

2024-01-03 06:09 UTC, Sachin-dot-py commented
Resolved the conflicts arising from merging PR #67

2024-01-11 23:38 UTC, Sachin-dot-py commented
@emergenitro @juzcallmekaushik anyone able to make the requested changes?

2024-01-12 00:03 UTC, juzcallmekaushik commented
> ?

I am working on the recode rn.. I will add it into the AR24

2024-01-12 05:50 UTC, Sachin-dot-py commented
Alright, closing this PR as per your comment.

2024-01-12 05:50 UTC, closed without merging